% Lists the names of all the features, (keeps main script more tidy).

function [feature_name_list] = feature_name_list()

feature_name_list = ...
["Level 1 Bid Price", "Level 1 Bid Size", "Level 1 Ask Price", "Level 1 Ask Size", ... 
"Level 2 Bid Price", "Level 2 Bid Size", "Level 2 Ask Price", "Level 2 Ask Size", ...
"Level 3 Bid Price", "Level 3 Bid Size", "Level 3 Ask Price", "Level 3 Ask Size", ...
"Level 4 Bid Price", "Level 4 Bid Size", "Level 4 Ask Price", "Level 4 Ask Size", ...
"Level 5 Bid Price", "Level 5 Bid Size", "Level 5 Ask Price", "Level 5 Ask Size", ...
"Level 6 Bid Price", "Level 6 Bid Size", "Level 6 Ask Price", "Level 6 Ask Size", ...
"Level 7 Bid Price", "Level 7 Bid Size", "Level 7 Ask Price", "Level 7 Ask Size", ...
"Level 8 Bid Price", "Level 8 Bid Size", "Level 8 Ask Price", "Level 8 Ask Size", ...
"Level 9 Bid Price", "Level 9 Bid Size", "Level 9 Ask Price", "Level 9 Ask Size", ...
"Level 10 Bid Price", "Level 10 Bid Size", "Level 10 Ask Price", "Level 10 Ask Size"];

end